### ISSUE TITLE
Flask -> Django 마이그레이션

### ISSUE THREAD

**Issue by TGoddessana** [crescenders/crescendo-backend#10]
1. 기존에 사용중이던 Flask-smorest 의 swagger 문서화 지원이 부족하다는 점
2. FastAPI 와 같은 프레임워크를 새로 사용하기에는 리소스가 너무 많이 든다는 점
3. 시간이 촉박하다는 점

을 고려해 Flask -> Django로 빠른 마이그레이션을 진행하겠음..

**Comment by thyeone** [comment]
🥲
